// ── DEPRECATED — demo-sync-all-casinos ───────────────────────────────────────
//
// This function previously generated synthetic demo_players and
// demo_behavioral_insights rows using Math.random().  It has been retired
// because:
//
//   1. All live data now flows through casino-simulator → live_events →
//      CasinoDataContext (single source of truth).
//   2. The demo_players / demo_behavioral_insights tables are no longer read
//      by any UI component.
//   3. The function had no effective auth guard (checked legacy RISK_ANALYST /
//      EXECUTIVE roles that no longer exist in the auth system).
//
// If you need to seed demo data use `scripts/seed-players.ts` locally or
// trigger the casino-simulator edge function (which marks events
// `is_simulated: true`).
//
// This endpoint now returns 410 Gone so any stale cron/webhook that still
// calls it fails loudly rather than silently injecting stale fake data.

import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, Authorization, X-Client-Info, Apikey",
};

Deno.serve((req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { status: 200, headers: corsHeaders });
  }

  return new Response(
    JSON.stringify({
      error: "deprecated",
      message:
        "demo-sync-all-casinos has been retired. " +
        "Live demo data is now generated by the casino-simulator function " +
        "(events are marked is_simulated: true). " +
        "Remove any cron schedules or webhooks pointing to this endpoint.",
    }),
    {
      status: 410,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    },
  );
});
